version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-service:3306/desafio_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=@Teste123
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect

  mysql-service:
    build:
      context: .
      dockerfile: Dockerfile-sql
    environment:
      - MYSQL_DATABASE=desafio_backend
      - MYSQL_USER=root
      - MYSQL_PASSWORD=@Teste123
      - MYSQL_ROOT_PASSWORD=@Teste123
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
