# Utilize a imagem do MySQL
FROM mysql:8.0

# Configuração de ambiente para o MySQL
ENV MYSQL_DATABASE=desafio_backend
ENV MYSQL_USER=admin
ENV MYSQL_PASSWORD=admin
ENV MYSQL_ROOT_PASSWORD='@Teste123'

# Adicione o arquivo SQL para inicializar seu banco de dados
ADD setup.sql /docker-entrypoint-initdb.d/

# Configura a porta padrão do MySQL
EXPOSE 3306
